### ISSUE TITLE
[Request] Buff / consumable

### ISSUE THREAD

**Issue by neowutran** [Gl0/TeraDataExtractor#3]
If you can extract consumable / buff ( crit power scroll, crit factor scroll, noctenium, canephora etc ..) , I will now be able to display them. 
(abnormality, to be able to display the uptime for each buff / consummable, like I did for endurance debuff)

**Comment by Gl0** [comment]
Add some, check what I forgot.
Some skill bindings are very strange =)

**Comment by neowutran** [comment]
Thanks =) I will try that tomorrow

**Comment by Gl0** [comment]
Updated again. Method enum is something ununderstandable...

**Comment by Gl0** [comment]
Filter out some abnormalities
