### ISSUE TITLE
[request] Ninja support

### ISSUE THREAD

**Issue by neowutran** [Gl0/TeraDataExtractor#4]
if you want/need a database => https://cloud.neowutran.ovh/index.php/s/rdBntVUuNomLvY1

**Comment by Gl0** [comment]
Don't see KR database there
https://github.com/Gl0/TeraDataExtractor/commit/9f4912a886f9b2946b590c8d3c931b8b90ffca36 not working?

**Comment by neowutran** [comment]
some skills are missing 
https://github.com/neowutran/ShinraMeter/issues/21#issuecomment-187767238

(and for the database, I forgot to upload it x) the upload will be over in 10min)

**Comment by Gl0** [comment]
seems to be fixed (may be missed something)
