### ISSUE TITLE
[request][bug] Remove special char

### ISSUE THREAD

**Issue by neowutran** [Gl0/TeraDataExtractor#5]
With the french database: 

`<Monster name="Prise de Montori&nbsp;: 21e défi" id="886011" isBoss="False" hp="0" />`

We have a special char (non breakable space "&nbsp;"), can you remove special char?

**Comment by Gl0** [comment]
Probably fixed.
Not sure, how it appears in source xml, since you haven't updated your decrypted database repo.

**Comment by neowutran** [comment]
ok =) 
I m uploading the new EU databases
